name: "printing workflow"

on: 
    workflow_dispatch: 

jobs:
    say-hello:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "Hello everyone from Ammar"

    execute-python:
        runs-on: ubuntu-24.04
        steps:
            - run: print("The sum of 5 and 10 is", 5+10)
              shell: python

    say-hello-external-action:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d # v1.1
            #- uses: actions/hello-world-javascript-action@v1 # This would work, but it would be less stable and less secure:
                with:
                    who-to-greet: "from an action in the GitHub Action marketplace! 👋"

    execute-after-python:
        runs-on: ubuntu-24.04
        needs:
            - execute-python
            - say-hello-external-action
        steps:
            - run: echo "executed after the python completed"