name: "printing workflow"

on: 
    workflow_dispatch: 

jobs:
    say-hello:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "Hello everyone from Ammar"
    say-hello-from-bash:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "Hello from bash shell"
              shell: bash
    say-hello-from-python:
        runs-on: ubuntu-24.04
        steps:
            - run: print("The sum of 5 and 10 is", 5+10)
              shell: python